version: '3.9'
services:
  backend:
    build: ./api_server
    volumes:
      - ./api_server:/api_server
    ports:
      - 8000:1234
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vite_react_spa
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    ports:
      - 4443:4443
    volumes:
      - ./.data:/data/vite_react_spa_dev
      - ./.storage:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443 -external-url http://${URL:-gcs}:4443 -port-http 8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/src
      - ./api_server/app/swagger:/src/swagger
    ports:
      - 5173:5173
      - 6006:6006
    tty: true
    stdin_open: true
