openapi: 3.0.0
info:
  title: Reading Records Controller Schema
  version: 1.0.0

paths:
  /searchBooks:
    get:
      operationId: searchBooks
      description: 書籍情報検索
      parameters:
        - name: keyword
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 読書記録の一覧取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchBooksResponseDto'
        '401':
          $ref: '../errors.yml#responses/401'

components:
  schemas:
    SearchBooksResponseDto:
      $ref: './components/search_books_response.dto.yml'
    SearchBooksResultDto:
      $ref: './components/search_books_result.dto.yml'
