substitutions:
  _IMAGE: 'api-server-prod/latest'
  _REGION: 'asia-northeast1'
  _SERVICE: 'reading-record'
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE',
        '-f',
        './deploy.Dockerfile',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE} \
          --project ${PROJECT_ID} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --add-cloudsql-instances "$$DATABASE_INSTANCE_NAME" \
          --update-env-vars="DATABASE_URL=$$DATABASE_URL,BOOKS_API_ENDPOINT=$$BOOKS_API_ENDPOINT,BOOKS_API_APPLICATION_ID=$$BOOKS_API_APPLICATION_ID,GCS_KEY_FILE_PATH=$$GCS_KEY_FILE_PATH,BUCKET_NAME=$$BUCKET_NAME,JWT_SECRET=$$JWT_SECRET"
    secretEnv:
      [
        'DATABASE_INSTANCE_NAME',
        'DATABASE_URL',
        'BOOKS_API_ENDPOINT',
        'BOOKS_API_APPLICATION_ID',
        'GCS_KEY_FILE_PATH',
        'BUCKET_NAME',
        'JWT_SECRET',
      ]
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DATABASE_INSTANCE_NAME/versions/latest'
      env: DATABASE_INSTANCE_NAME
    - versionName: 'projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/latest'
      env: DATABASE_URL
    - versionName: 'projects/${PROJECT_ID}/secrets/BOOKS_API_ENDPOINT/versions/latest'
      env: BOOKS_API_ENDPOINT
    - versionName: 'projects/${PROJECT_ID}/secrets/BOOKS_API_APPLICATION_ID/versions/latest'
      env: BOOKS_API_APPLICATION_ID
    - versionName: 'projects/${PROJECT_ID}/secrets/GCS_KEY_FILE_PATH/versions/latest'
      env: GCS_KEY_FILE_PATH
    - versionName: 'projects/${PROJECT_ID}/secrets/BUCKET_NAME/versions/latest'
      env: BUCKET_NAME
    - versionName: 'projects/${PROJECT_ID}/secrets/JWT_SECRET/versions/latest'
      env: JWT_SECRET
