openapi: 3.0.0
info:
  title: Auth Controller Schema
  version: 1.0.0
paths:
  /auth/validateSignUp:
    post:
      operationId: validateSignUp
      description: 会員登録のバリデーションチェック
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '201':
          description: バリデーションチェック成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateSignUpResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                description: バリデーションエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: array
                    items:
                      description: バリデーションエラーのレスポンスのDTO
                      type: string
                  error:
                    type: string
                required:
                  - statusCode
                  - message
                  - error
  /auth/signUp:
    post:
      operationId: signUp
      description: 会員登録実行
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '201':
          description: 会員登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                description: バリデーションエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: array
                    items:
                      description: バリデーションエラーのレスポンスのDTO
                      type: string
                  error:
                    type: string
                required:
                  - statusCode
                  - message
                  - error
  /auth/signIn:
    post:
      operationId: signIn
      description: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInDto'
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponseDto'
  /auth/checkSignedIn:
    get:
      operationId: checkSignedIn
      description: 認証済みかどうかをチェック
      parameters: []
      responses:
        '200':
          description: 認証済みかどうかチェック成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/checkSignedInResponseDto'
components:
  schemas:
    SignUpDto:
      description: 読書記録作成のrequest DTO
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        passwordConfirm:
          type: string
      required:
        - title
        - email
        - password
        - passwordConfirm
    ValidateSignUpResponseDto:
      description: 会員登録のバリデーションチェックのレスポンスDTO
      type: object
      properties:
        errors:
          type: object
          properties:
            name:
              type: array
              items:
                type: string
            email:
              type: array
              items:
                type: string
            password:
              type: array
              items:
                type: string
            passwordConfirm:
              type: array
              items:
                type: string
      required:
        - errors
    SignUpResponseDto:
      description: 会員登録のレスポンスDTO
      type: object
      properties:
        result:
          type: boolean
      required:
        - result
    SignInDto:
      description: Sign in params.
      type: object
      properties:
        email:
          type: string
          example: test@example.com
        password:
          type: string
        errors:
          type: array
          items:
            description: バリデーションエラーメッセージ
            type: string
      required:
        - email
        - password
    SignInResponseDto:
      description: ログインのレスポンス
      type: object
      properties:
        errors:
          type: array
          items:
            description: バリデーションエラーメッセージ
            type: string
      required:
        - errors
    checkSignedInResponseDto:
      description: 認証済みかどうかチェックのレスポンスDTO
      type: boolean
