name: backend_unit_test

on:
  pull_request:
    paths:
      - 'api_server/app/src/**/*.ts'
      - 'api_server/app/package.json'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.28
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vite_react_spa_test
          TZ: 'Asia/Tokyo'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./api_server/app
        run: npm install

      - name: Run Unit tests
        working-directory: ./api_server/app
        env:
          IS_CI: true
        run: |
          npm run test
